#!/usr/bin/env python3
"""Generates board/src/assets.h: 64x64 land mask of Europe/Africa/W-Asia and the stork splash sprite.
Needs: pip install "geopandas<1.0" shapely pillow numpy   (map data ships with geopandas, no download)"""
import sys, warnings, os
warnings.filterwarnings("ignore")
import numpy as np
from PIL import Image, ImageDraw
import geopandas as gpd

LON0, LAT0, PXDEG, SIZE = -20.0, 58.0, 0.72, 64      # keep in sync with board/src/main.cpp (written into assets.h)

def land_mask():
    world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
    SS = 8
    img = Image.new("L", (SIZE*SS, SIZE*SS), 0); d = ImageDraw.Draw(img)
    def proj(lon, lat): return ((lon-LON0)*PXDEG*SS, (LAT0-lat)*PXDEG*SS)
    for geom in world.geometry:
        polys = list(geom.geoms) if geom.geom_type == "MultiPolygon" else [geom]
        for p in polys:
            d.polygon([proj(x, y) for x, y in p.exterior.coords], fill=255)
            for h in p.interiors: d.polygon([proj(x, y) for x, y in h.coords], fill=0)
    small = img.resize((SIZE, SIZE), Image.BOX)
    return (np.array(small) >= 110)          # slightly generous so thin coasts survive

def pack(bits):                               # row-major, LSB first = U8g2 XBM format
    h, w = bits.shape; out = []
    for y in range(h):
        for bx in range(0, w, 8):
            v = 0
            for k in range(8):
                if bx+k < w and bits[y, bx+k]: v |= 1 << k
            out.append(v)
    return out

def stork():
    # standing white stork facing right: white body, black wing patch, long neck, long beak, long legs
    S, W, H = 10, 44, 60
    im = Image.new("L", (W*S, H*S), 0); d = ImageDraw.Draw(im)
    def P(pts, fill=255): d.polygon([(x*S, y*S) for x, y in pts], fill=fill)
    def L(pts, w, fill=255): d.line([(x*S, y*S) for x, y in pts], fill=fill, width=int(w*S), joint="curve")
    # legs (long, thin) with feet
    L([(21, 38), (22, 50), (21.5, 58)], 1.3); L([(21.5, 58), (26, 58.6)], 1.3)
    L([(25, 38), (27, 50), (28, 57)], 1.3); L([(28, 57), (32, 57.8)], 1.3)
    # body: plump oval leaning slightly, tail to the left
    d.ellipse((9*S, 20*S, 33*S, 40*S), fill=255)
    P([(11, 24), (3, 31), (6, 34), (14, 33)])
    # neck: S curve up to the head
    L([(28, 25), (32, 20), (31, 13), (33, 8)], 3.2)
    d.ellipse((30.5*S, 4.5*S, 36.5*S, 10.5*S), fill=255)
    # long beak
    P([(36, 6.2), (44, 8.4), (36, 9.4)])
    # eye
    d.ellipse((33.6*S, 6.2*S, 34.8*S, 7.4*S), fill=0)
    # wing: black flight-feather panel with white outline gap
    P([(10, 28), (24, 25), (30, 31), (22, 38), (12, 36)], fill=0)
    P([(13, 29.5), (23, 27.5), (27, 31.5), (21, 35.5), (14, 34.5)], fill=255)
    for x0 in (13, 15.5, 18, 20.5, 23):
        L([(x0, 31.5), (x0 + 1.2, 35.2)], 0.7, fill=0)
    small = im.resize((W, H), Image.LANCZOS)
    return (np.array(small) >= 110), W, H

def emit_array(name, data):
    lines = []
    for i in range(0, len(data), 16): lines.append("  " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",")
    return "static const uint8_t %s[] PROGMEM = {\n%s\n};\n" % (name, "\n".join(lines))

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "../board/src/assets.h"
    land = land_mask(); sp, W, H = stork()
    with open(out, "w") as f:
        f.write("// generated by tools/make_assets.py - do not edit\n#pragma once\n#include <Arduino.h>\n")
        f.write("#define MAP_LON0 %.2ff\n#define MAP_LAT0 %.2ff\n#define MAP_PXDEG %.3ff\n#define MAP_SIZE %d\n" % (LON0, LAT0, PXDEG, SIZE))
        f.write("#define STORK_W %d\n#define STORK_H %d\n" % (W, H))
        f.write(emit_array("MAP_LAND", pack(land))); f.write(emit_array("STORK_BMP", pack(sp)))
    # previews
    Image.fromarray((~land*255).astype("uint8")).resize((SIZE*6, SIZE*6), Image.NEAREST).save(os.path.join(os.path.dirname(os.path.abspath(out)), "../../preview/map.png"))
    Image.fromarray((sp*255).astype("uint8")).resize((W*8, H*8), Image.NEAREST).save(os.path.join(os.path.dirname(os.path.abspath(out)), "../../preview/stork.png"))
    print("wrote", out)
main()
